### ISSUE TITLE
请添加可以预览的测试版本

### ISSUE THREAD

**Issue by luoliwoshang** [lucky-aeon/community#123]
请告诉我你们对于此事的态度

**Comment by xhyqaq** [comment]
> 请告诉我你们对于此事的态度

我们预计在这周的星期日之前做完，并且给您颁发 `嘉宾` label

**Comment by xhyqaq** [comment]
> 请告诉我你们对于此事的态度

很抱歉的通知您，我们延期发版了，延期日期不固定 
![0253011B](https://github.com/lucky-aeon/community/assets/73917396/93c3b6e2-d054-4bca-a517-d385f90fa4bf)

**Comment by luoliwoshang** [comment]
> > 请告诉我你们对于此事的态度
> 
> 很抱歉的通知您，我们延期发版了，延期日期不固定 ![0253011B](https://private-user-images.githubusercontent.com/73917396/316369710-93c3b6e2-d054-4bca-a517-d385f90fa4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzMxMzEsIm5iZiI6MTcxMTM3MjgzMSwicGF0aCI6Ii83MzkxNzM5Ni8zMTYzNjk3MTAtOTNjM2I2ZTItZDA1NC00YmNhLWE1MTctZDM4NWY5MGZhNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Mzc4NDAwNzM4NGU4ODE4OTc0NzUzZTEwYmU1YjNhMDhkYTdiMDI3MDBkMjNhMThlYWY5NDU1NTE2NjQzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4VvzMCn--vMP6Dv0LFwms2dNi4TNzQwKsRSGIvDSyg)

好的，等待你们的测试版本

**Comment by xhyqaq** [comment]
> > > 请告诉我你们对于此事的态度
> > 
> > 
> > 很抱歉的通知您，我们延期发版了，延期日期不固定 ![0253011B](https://private-user-images.githubusercontent.com/73917396/316369710-93c3b6e2-d054-4bca-a517-d385f90fa4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzMxMzEsIm5iZiI6MTcxMTM3MjgzMSwicGF0aCI6Ii83MzkxNzM5Ni8zMTYzNjk3MTAtOTNjM2I2ZTItZDA1NC00YmNhLWE1MTctZDM4NWY5MGZhNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Mzc4NDAwNzM4NGU4ODE4OTc0NzUzZTEwYmU1YjNhMDhkYTdiMDI3MDBkMjNhMThlYWY5NDU1NTE2NjQzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4VvzMCn--vMP6Dv0LFwms2dNi4TNzQwKsRSGIvDSyg)
> 
> 好的，等待你们的测试版本

ok了！给您私发 code

**Comment by luoliwoshang** [comment]
> > > > 请告诉我你们对于此事的态度
> > > 
> > > 
> > > 很抱歉的通知您，我们延期发版了，延期日期不固定 ![0253011B](https://private-user-images.githubusercontent.com/73917396/316369710-93c3b6e2-d054-4bca-a517-d385f90fa4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzMxMzEsIm5iZiI6MTcxMTM3MjgzMSwicGF0aCI6Ii83MzkxNzM5Ni8zMTYzNjk3MTAtOTNjM2I2ZTItZDA1NC00YmNhLWE1MTctZDM4NWY5MGZhNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEzMjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Mzc4NDAwNzM4NGU4ODE4OTc0NzUzZTEwYmU1YjNhMDhkYTdiMDI3MDBkMjNhMThlYWY5NDU1NTE2NjQzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4VvzMCn--vMP6Dv0LFwms2dNi4TNzQwKsRSGIvDSyg)
> > 
> > 
> > 好的，等待你们的测试版本
> 
> ok了！给您私发 code

好的，已经收到，祝好
