### ISSUE TITLE
feat(QA模块): QA列表显示状态信息

### ISSUE THREAD

**Issue by xhyqaq** [lucky-aeon/community#148]
- 忽视 QA 下 分类有文章，正在修

![image](https://github.com/lucky-aeon/community/assets/73917396/6909143c-793e-4e39-8c8f-0154db9a0b74)

![image](https://github.com/lucky-aeon/community/assets/73917396/178f2dc2-9f67-4cef-bfd6-76cd5eb085f4)

**Comment by LiusCraft** [comment]
这个已经实现了
