### ISSUE TITLE
feat: add the article module

### ISSUE THREAD

**Issue by xhyqaq** [lucky-aeon/community#15]
# Desc

- The article has crud likes and views. The most important thing is the status

- Status：Draft、Publish、Pending、Resolved、Closed

- Articles are managed by categories

- The status of articles in different categories is also different

- Basic classification：All、QA、Project & QA、technology sharing ...

- Only QA has additional status: pending/resolved/closed

# The article module function list

- [x] #26
- [ ] Article likes and views
- [ ]  Article type
- [ ] User's article list

...To be added

**Comment by LiusCraft** [comment]
https://github.com/lucky-aeon/community/issues/25

**Comment by AnushkaSharma04** [comment]
I want to contribute to this . Can you guide me ?

**Comment by xhyqaq** [comment]
> I want to contribute to this . Can you guide me ?

**no problem！**


# Let me talk about the design and process

## Package struct

assets：the static file
cmd：the project start file，There may be multiple projects，Each project has its own routing and middleware
docs：doc
pkg：public file，example：config
server：backend
views：frondend


## Architecture design

The project uses a monolithic architecture and a back-end-focused approach, which means you also need to participate in front-end development.

Rendering using go templates


### The Simple development process：
- definition view router ：Jump to specified page
- definition router ：process flow logic
- return the view and carry the data

### refer to：

model：server/model/user.go
dao：server/dao/user.go
service：server/service/user.go
router：cmd/community/routers/user.go  ： **Learn to jump pages and carry data**
core：pkg/service_context/context.go     ： core file

#### config：
If you need to involve file-related development, you also need to configure additional Qiniu Cloud object storage configuration.


=============================

**You can select what interests you and submit it as a question. Of course, it must be a function that is needed at this stage.**

**Comment by xhyqaq** [comment]
> I want to contribute to this . Can you guide me ?

sorrt！！！, we are now changing to a front-end and back-end separation architecture, please wait for the latest news
