### ISSUE TITLE
前台页面删除不必要元素

### ISSUE THREAD

**Issue by xhyqaq** [lucky-aeon/community#167]
- 普通用户不需要显示后台管理的入口
- 顺便把左边的空白清掉

![image](https://github.com/lucky-aeon/community/assets/73917396/7f47e1f0-f847-4b86-bf44-791c941e3dcc)

**Comment by LiusCraft** [comment]
不要header？或者是清掉了放什么？

**Comment by xhyqaq** [comment]
> 不要header？或者是清掉了放什么？

不要左边的灰色块块，先清掉，还没给咱社区想名字，不知道
